/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CarbonAsleepFilled: typeof import('~icons/carbon/asleep-filled')['default']
    CarbonResult: typeof import('~icons/carbon/result')['default']
    CarbonSun: typeof import('~icons/carbon/sun')['default']
    EventSelect: typeof import('./src/components/EventSelect/EventSelect.vue')['default']
    GlobalHeader: typeof import('./src/components/GlobalHeader/GlobalHeader.vue')['default']
    ResultsAgeFilter: typeof import('./src/components/Results/ResultsFilters/ResultsAgeFilter.vue')['default']
    ResultsCategoryFilter: typeof import('./src/components/Results/ResultsFilters/ResultsCategoryFilter.vue')['default']
    ResultsFilters: typeof import('./src/components/Results/ResultsFilters/ResultsFilters.vue')['default']
    ResultsGenderFilter: typeof import('./src/components/Results/ResultsFilters/ResultsGenderFilter.vue')['default']
    ResultsTable: typeof import('./src/components/Results/ResultsTable/ResultsTable.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
